### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by zheoreh** [ShogunPanda/fastimage#1]
ReferenceError: Promise is not defined
  at Object.module.exports.filteredInfo (/home/zhe/projects/pindorse/node_modules/fastimage/lib/core.js:219:18)
  at Object.module.exports.size (/home/zhe/projects/pindorse/node_modules/fastimage/main.js:89:19)
  at Object.<anonymous> (/home/zhe/projects/pindorse/pindorse/general/serverApiHandlers.coffee:34:23)
  at [object Object].exports.each (/home/zhe/projects/pindorse/node_modules/cheerio/lib/api/traversing.js:293:24)
  at Request._callback (/home/zhe/projects/pindorse/pindorse/general/serverApiHandlers.coffee:26:18)
  at Request.self.callback (/home/zhe/projects/pindorse/node_modules/request/request.js:360:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (/home/zhe/projects/pindorse/node_modules/request/request.js:1202:14)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/home/zhe/projects/pindorse/node_modules/request/request.js:1150:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:943:16
  at process._tickCallback (node.js:419:13)

**Comment by ShogunPanda** [comment]
Can you please give me informations about the platform and 
Which platform are you on? Which version of node.js/io.js are you using?

**Comment by drora** [comment]
+1 on that:
ReferenceError: Promise is not defined
at Object.module.exports.filteredInfo (/code/node_modules/fastimage/lib/core.js:219:18)
...

**Comment by drora** [comment]
I think I got it:
line#[core.js:219:18] = 'return new Promise(function(complete, reject){'
Promise is only implemented and part of ES6 (stable nodejs 0.12)
anyway, the docs state that this module requires min node version of 0.10, which apparently is a mistake

**Comment by ShogunPanda** [comment]
Yup, probably I misread the documentation. I'll fix it ASAP. 
Thanks for the reports!

**Comment by ShogunPanda** [comment]
What is funny, tho, is that the build passed on Travis for 0.10. Weird! XD

**Comment by ShogunPanda** [comment]
Fix released on 1.0.1. Enjoy and let me know if it still happens.

**Comment by zheoreh** [comment]
Thank. My node version is 0.10.33

**Comment by CrazyAlvaro** [comment]
I got kind of the same error when try to run test on it. (my node version is 0.12.2)

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'promise'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/yechen/Github/fastimage/lib/core.js:24:19
```

resolved the issue after manually installed promise

```
npm install promise
```

Maybe it will help if you could add promise as "devDependencies" inside  package.json file : )

**Comment by ShogunPanda** [comment]
@CrazyAlvaro OMG! I though I already did that. Ok, will fix ASAP.
